name: codeua

services:
  minigames:
    build:
      context: .
      dockerfile: Dockerfile
    image: codeua:${APP_VERSION}
    pull_policy: missing
    container_name: codeua
    restart: always
    env_file:
      - src/assets/.env
    volumes:
      - ./src/assets/locales:/app/src/assets/locales
      - ./src/assets/sounds:/app/src/assets/sounds
    ports:
      - "8006:8080"
